### ISSUE TITLE
Where is labeled_images.tar.gz

### ISSUE THREAD

**Issue by 578123043** [herobd/NAF_dataset#1]
I dont find it in https://github.com/herobd/NAF_dataset. Could you add a 
Hyperlink in Readme.md?

**Comment by dhana-sekhar** [comment]
hello , you can find the labeled_images.tar.gz in releases as mentioned below.
![release](https://user-images.githubusercontent.com/23493757/64937845-7c537f00-d879-11e9-8284-5d1b312ac5d9.png)

**Comment by 578123043** [comment]
![image](https://user-images.githubusercontent.com/16147509/64941630-cb111100-d899-11e9-90ea-ea120af7a697.png)
I cont find it. Clould you help me .

**Comment by 578123043** [comment]
https://github.com/herobd/NAF_dataset/releases
